const keys = {
    TAB: "Tab",
    ENTER: "Enter",
    PAUSE: "Pause",
    ESCAPE: "Escape",
    SPACE: "Space",

    PAGE_UP: "PageUp",
    PAGE_DOWN: "PageDown",
    END: "End",
    HOME: "Home",
    LEFT_ARROW: "ArrowLeft",
    UP_ARROW: "ArrowUp",
    RIGHT_ARROW: "ArrowRight",
    DOWN_ARROW: "ArrowDown",

    INSERT: "Insert",
    DELETE: "Delete",

    ZERO: "Digit0",
    ONE: "Digit1",
    TWO: "Digit2",
    THREE: "Digit3",
    FOUR: "Digit4",
    FIVE: "Digit5",
    SIX: "Digit6",
    SEVEN: "Digit7",
    EIGHT: "Digit8",
    NINE: "Digit9",

    A: "KeyA",
    B: "KeyB",
    C: "KeyC",
    D: "KeyD",
    E: "KeyE",
    F: "KeyF",
    G: "KeyG",
    H: "KeyH",
    I: "KeyI",
    J: "KeyJ",
    K: "KeyK",
    L: "KeyL",
    M: "KeyM",
    N: "KeyN",
    O: "KeyO",
    P: "KeyP",
    Q: "KeyQ",
    R: "KeyR",
    S: "KeyS",
    T: "KeyT",
    U: "KeyU",
    V: "KeyV",
    W: "KeyW",
    X: "KeyX",
    Y: "KeyY",
    Z: "KeyZ",
};

export { keys }