name: Build and GH-Page Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        run: yarn install

      - name: Build
        run: |
          yarn autoclean
          yarn build

      - name: Deploy to GH Page
        uses: ninjacole/asteroidsts@main
        with:
          branch: gh-pages
          folder: dist
